### ISSUE TITLE
Allow privileged tools to schedule un-scheduled TaskCluster tasks

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#132]
For buildbot we use buildapi but for TaskCluster I have no idea.

**Comment by armenzg** [comment]
The model we're going to follow is using an API to remove the last dependency on a task to allow it to run:
https://groups.google.com/forum/#!topic/mozilla.tools/Uw_KQncI_Us

This is another way that we can schedule tasks which we won't follow:
https://bugzilla.mozilla.org/show_bug.cgi?id=1174236

**Comment by vaibhavmagarwal** [comment]
Now that we have a TC script at: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/scripts/misc/taskcluster_retrigger.py
can we rename this issue for a more appropriate cause, or should we close it?

**Comment by armenzg** [comment]
We can retrigger an existing task, however, we can't retrigger a non-existent task.
I will rewrite the summary.

This depends on:
https://bugzilla.mozilla.org/show_bug.cgi?id=1178516

**Comment by armenzg** [comment]
The model we're going to follow is using an API to remove the last dependency of a task on an existing task graph to allow it to run [1].

This depends on:
* Bug 1178516 - scheduler: New big graph scheduler
* Bug 1146025 - gecko: decision task should export task graph extension as artifact

I say privileged tools since scheduling on TaskCluster or removing dependencies through the command line is not necessarily something we can do without "Bug 1198360 - Support scheduling Buildbot builders on mozci from the command line (through TaskCluster and BBB)" [3]

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1178516
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1146025
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=1198360

**Comment by armenzg** [comment]
I think this will be something we would like to look into next quarter. Probably me.

**Comment by armenzg** [comment]
@xennygrimmato your work will help me with this task. What issue or bug where we using to track your work?

**Comment by xennygrimmato** [comment]
@armenzg This one here [1].

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1232005

**Comment by armenzg** [comment]
Great!
I will track it on bugzilla.

**Comment by armenzg** [comment]
This has been solved with Action Tasks by @martiansideofthemoon
