### ISSUE TITLE
Determine which functionality of platforms.py is needed for TaskCluster support

### ISSUE THREAD

**Issue by adusca** [mozilla/mozilla_ci_tools#152]
Almost every function in platforms.py depends on allthethings.json and TaskCluster jobs are not in it. For TaskCluster support we would need to either not use those functions or write a TaskCluster compatible version of them.

**Comment by armenzg** [comment]
I'm hoping to fix this once I start talking with the Firefox OS automation team.

**Comment by adusca** [comment]
Most of the functions in 'platforms.py' would probably not be very useful for TaskCluster.

One possible exception is build_tests_per_platform_graph [1] that is used in write_tests_per_platform_graph.py. If the script is going to be used for a dynamic Trychooser, it might be useful to also build the mapping for TC jobs. Another solution for that would be using write_tests_per_platform_graph.py just to implement the Buildbot side of things and something else (possibly not involving mozci) on TC side.

[1] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/platforms.py#L187

**Comment by armenzg** [comment]
I think we should always be reminded that whatever works for TaskCluster it does not mean it should work for TaskCluster.

I believe this should depend on 
* Bug 1146025 - gecko: decision task should export task graph extension as artifact

Given a task graph being published we could then fetch it and use it in the same way we use "allthethings.json" for Buildbot.

We might also use code from here [2] as inspiration to generate meta data from the gecko tree if we would like to.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1146025
[2] https://reviewboard.mozilla.org/r/11423/diff/1#index_header

**Comment by armenzg** [comment]
I will close this. I will be tackling as whole next quarter and the issue as is does not help me.
