### ISSUE TITLE
buildapi.py should not let you try to schedule a builder which does not exist

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#177]
validate a builder before making a request:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L40

This way we prevent submitting bad data to self-serve/buildapi.

**Comment by vaibhavmagarwal** [comment]
We do validate the buildername in mozci.py: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/mozci.py#L297

I had previously changed it, but now it is back to original

**Comment by armenzg** [comment]
I think is good to highlight bad builders early on mozci.py, however, if we call _make_request directly it should also validate the data.

**Comment by armenzg** [comment]
Under trigger_arbitrary_job() we should verify that the builder is valid before trying to make the post request:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L30

**Comment by armenzg** [comment]
Right now, the buildapi code lives in a different repo.
Hence, not having knowledge of allthethings.json (where the data lives to determine valid builders).

We could try to determine if Buildapi recognizes the builder after a post [1], however, from my initial comment (and my memory), Buildapi won't tell you that you submitted a bad buildername. In fact, someone will have to go and clean up the request from the database.
There is no validation as far as I can tell [2].

In other words, we can't make buildapi_client safer without making it more complicated.

I believe we should add a note on Buildapi client to say that using such function without using mozci could lead inserting bad buildernames into the database. Using mozci's ci_manager is recommended.

On the other hand, we can validate in BuildAPIManager [3]
We could move valid_builder() from mozci to BuildAPIManager as a private method (maybe an independent function rather than a private member of the class).
We should leave a valid_builder() stub in mozci.py just for backward compatibility (rather than having to fix other external users like pulse_actions). We should make calls in this repo to the original valid_builder() to be instead calls to the new _valid_builder() under ci_manager.py

Let me know if this does not make sense.

[1] https://github.com/armenzg/buildapi_client/blob/master/buildapi_client/buildapi_client.py#L29
[2]
https://github.com/mozilla/build-buildapi/blob/a19f3d79dd78e221a763b341f7c2d8281bea94a7/buildapi/controllers/selfserve.py#L511
https://dxr.mozilla.org/build-central/source/buildapi/buildapi/lib/mq.py#246
[3] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/ci_manager.py#L70

**Comment by MikeLing** [comment]
Hello @armenzg, 
> We could move valid_builder() from mozci to BuildAPIManager as a private method (maybe an independent function rather than a private member of the class).

Do we have the valide_builder() function in mozci.py? I think we only have query_builders() in it and we need to validate builder name by ourselves. :)

> We should leave a valid_builder() stub in mozci.py just for backward compatibility (rather than having to fix other external users like pulse_actions). We should make calls in this repo to the original valid_builder() to be instead calls to the new _valid_builder() under ci_manager.py

So, we need to 'create' a valide_builder() function in mozci.py and call _valide_builder() which in ci_manager.py? And we need realize the valid_builder in ci_manager.py :)

Am I right? please correct me if I'm wrong. Thank you :)

**Comment by armenzg** [comment]
valid_builder():
https://github.com/mozilla/mozilla_ci_tools/blob/63a1de3ad416f5f5fa1976ec931d22b67a344886/mozci/mozci.py#L337

You understood it well! :+1:

**Comment by mandaltapesh** [comment]
@MikeLing  are you working on this ?

**Comment by MikeLing** [comment]
hey @mandaltapesh, no I haven't work on this issue. feel free to take it if you're interested on it: )

**Comment by MikeLing** [comment]
Due to @xennygrimmato said he has interesting in this issue and @mandaltapesh haven't take this for now. I think let xenny to work on this issue is a good ideal :)

**Comment by armenzg** [comment]
@xennygrimmato are you working on this? or can we put it back into the pool of available issues?

**Comment by mandaltapesh** [comment]
@xennygrimmato @armenzg @MikeLing   is this issue available ?

**Comment by armenzg** [comment]
This was fixed long time ago.
