### ISSUE TITLE
Readme and instructions are not usable for non-python-wizards

### ISSUE THREAD

**Issue by gijsk** [mozilla/mozilla_ci_tools#196]
I just want to retrigger some talos runs on some try pushes without mashing my mouse.

I was told that I needed to change the relevant script because otherwise I'd be triggering android builds. So I did that as per https://bugzilla.mozilla.org/show_bug.cgi?id=1163512#c17 .

Then I tried to run. That produces:

```
Gijs@X /e/dev/mozilla_ci_tools/mozci/scripts
$ python alltalos.py --times 14 --rev 188165e33ad0 --repo-name try
Traceback (most recent call last):
  File "alltalos.py", line 6, in <module>
    from mozci.mozci import trigger_job
ImportError: No module named mozci.mozci
```

Huh. Well, that clearly didn't work. Maybe I should be in the parent directory, or its parent?

That produces exactly the same error. So I start reading the README.rst. That says:

> Move inside the project directory, create a virtualenv_ (highly recommended)

I don't know what this is, but the internet tells me I should be able to run "virtualenv ENV" with ENV being a path where I want to create it. I know that talos just uses `.` for this, but also that it already provides all the scripts that the virtualenv docs go on about, and that it doesn't work on my mac because of weird issues with `hashlib` I spent 1 hour trying to figure out and then gave up on.

Anyway.

I try reading the docs on https://mozilla-ci-tools.readthedocs.org/en/latest/scripts.html

These also seem to believe running the script should Just Work, and make no mention of a virtualenv, so I'm back at square one.

Please please please update your docs so that people who do not know why they want a virtualenv can still use this tool.

**Comment by gijsk** [comment]
So I've `easy_install virtualenv` on my Windows box, and created a virtualenv, and activated it, and then running:

```
(virtualenv_) E:\dev\mozilla_ci_tools>python mozci/scripts/alltalos.py --times 14 --rev 188165e33ad0 --repo-name try
```

still produces:

```
Traceback (most recent call last):
  File "mozci/scripts/alltalos.py", line 6, in <module>
    from mozci.mozci import trigger_job
ImportError: No module named mozci.mozci
```

**Comment by vaibhavmagarwal** [comment]
Hi Gijs,

I am sorry that you are having problem with the documentation. I know it is not that great, and we will look in more to improve it.

To solve you problem, have you done: 'python setup.py develop' in the main folder?

**Comment by gijsk** [comment]
Ah! This helps, it seems.

I will note, which I forgot to mention in the previous comment, that on a Windows machine virtualenv will only generate bat files, which won't work in the mozilla-build bash shell (which has everything else I normally need, like hg, git, my editors, etc.). Can we include the relevant scripts in the repo instead?

**Comment by vaibhavmagarwal** [comment]
Gijs,

In the next release, we have packed the scripts inside the library itself, and they will be present when one does 'pip install mozci' to install the library. So, in the next release (going to do that today or tomorrow), one will be able to directly do:

$ mozci-alltalos --times 14 --rev 188165e33ad0 --repo-name try

instead of cloning the repository and doing 
$ python mozci/scripts/alltalos.py --times 14 --rev 188165e33ad0 --repo-name try

**Comment by gijsk** [comment]
I'm confused - don't I want to clone because I need to change the script in question? It seemed evil to get the package with pip/easy_install and then change the packaged files (plus, it'll get overwritten in new versions of the library...)

**Comment by vaibhavmagarwal** [comment]
Oh right, ignore my previous comment, I did not see that you needed to change the script, apologies.

**Comment by gijsk** [comment]
Maybe my earlier comment wasn't clear enough - I want the `*sh` versions of the *virtualenv* activate/deactivate scripts to be present in the repo on checkout, like they are for talos, so that you can just tell people "run `source bin/activate`" or whatever.

**Comment by vaibhavmagarwal** [comment]
Gijs,
Actually you don't need a virtualenv to run this package, you can directly do 'python setup.py develop' in the main directory and it will be fine. virtualenv just gives you better environment isolation and so it is recommended. Installing a virtualenv is a matter of choice, so I think we shouldn't include it by default in our repo, but I am open to more discussion (cc @armenzg , @adusca ). In the documentation if we write "virtualenv (recomended but not necessary)" will it be better?

**Comment by jgraham** [comment]
Running it outside a virtualenv is way worse.
You should look into the code that e.g. mach has to setup a virtualenv automatically. Including that kind of functionality seems appropriate.

**Comment by armenzg** [comment]
I think it is time to make mozci part of mach as @vaibhavmagarwal has recommended several times since developers are needing this tool under their belt.

Developers should not need to know what virtualenv is and let mach do the right thing.

Thoughts?
