### ISSUE TITLE
(mentored issue) Add unit tests to functions in buildapi.py

### ISSUE THREAD

**Issue by adusca** [mozilla/mozilla_ci_tools#243]
In this issue we are going to track functions that are good starting places for adding unit tests.

* [ _payload]
(https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L140)
* [_builders_api_url](https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L124)
* [_jobs_api_url](https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L133)

**Comment by armenzg** [comment]
Since we've moved buildapi into its own package, I've filled this:
https://github.com/armenzg/buildapi_client/issues/3
