### ISSUE TITLE
Use the full 20 byte / 40 character hashes for revisions

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#263]
> *all automation should use the full 20 byte / 40 character SHA-1 hashes*

In mozci we use the 12-char revisions:
```
MacAir ci_tools git:[master] $ grep -r "\[0:12\]" mozci
mozci/scripts/misc/find_status_for_jobs.py:                    'fromchange': schedule_info["revision"][0:12],
mozci/scripts/misc/find_status_for_jobs.py:                    'tochange': revision[0:12],
mozci/sources/buildapi.py:        return status_data["properties"]["revision"][0:12] != req["revision"][0:12]
mozci/sources/pushlog.py:        revisions.append(pushes[push_id]["changesets"][-1][0:12])
mozci/sources/pushlog.py:        revisions.append(pushes[str(push_id)]["changesets"][0][0:12])
```
For scripts, if we accept 12-char, we should see if we can find a unique match to its 40-char representation.
If we have collision we should fail.

For this:
https://secure.pub.build.mozilla.org/buildapi/self-serve/try/rev/98e9b20f9d4d
we should use this:
https://secure.pub.build.mozilla.org/buildapi/self-serve/try/rev/98e9b20f9d4d5e8b7fee9464324484d2adc78863

As a reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=1175655

**Comment by MikeLing** [comment]
Hey armenzg, due to I haven't found you on irc, so I decide to leave comment here and take this issue as my first bug for quarter of contribution. Is that ok?

**Comment by armenzg** [comment]
As we agreed on IRC, @MikeLing will be giving us a hand with this.
Let me or @adusca know if we can assist you.

**Comment by MikeLing** [comment]
Hi armenzg, @armenzg I meet some problems when I try to run 'tox'.  https://pastebin.mozilla.org/8851274

And as you said, I been authentication when I click those link you left above. What should I do next?

**Comment by armenzg** [comment]
Hi @MikeLing , in order to have access to buildapi you need LDAP credentials with scm_level of 1 (allowed to commit to try). Would you want to get commit privileges for try? Do you have experience with commiting code to Mercurial?
This is what Alice did to get access:
https://bugzilla.mozilla.org/show_bug.cgi?id=1136191
You would have to read this and agree to it:
https://www.mozilla.org/en-US/about/governance/policies/commit/

Can you run 'tox' without being inside of a virtualenv?
Tox sets up its own virtualenv under .tox/
I think it is conflicting with your mozci venv.

**Comment by MikeLing** [comment]
Hi @armenzg and @adusca , When I try to run 'find_status_for_jobs.py', it tells me **can't import _matching_jobs**. 

(mozici_env)MikeLings-MacBook-Pro-2:mozilla_ci_tools mikeling$ python mozci/scripts/misc/find_status_for_jobs.py -b 'Linux mozilla-inbound leak test build' -r ae33441d7f86
Traceback (most recent call last):
  File "mozci/scripts/misc/find_status_for_jobs.py", line 6, in <module>
    from mozci.mozci import query_repo_name_from_buildername, _matching_jobs, \
ImportError: cannot import name _matching_jobs

I also can't find the _matching_jobs in mozci in codebase either(https://github.com/mozilla/mozilla_ci_tools/search?utf8=%E2%9C%93&q=_matching_jobs). Is that mean I miss some dependence or something?

**Comment by armenzg** [comment]
Normally those scripts can fall out of date (the ones under 'misc').

I just checked the code but I would like you to find out for where the new version of _matching_jobs has ended up under. Hint: you can use tests to find it.

**Comment by armenzg** [comment]
This was fixed by @MikeLing 
Thanks!
https://github.com/mozilla/mozilla_ci_tools/pull/374
