### ISSUE TITLE
Re-factor _status_summary() to be less hard-coded

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#307]
Re-factor _status_summary() [1] to be less hard-coded. When I first wrote it, I knew it was a hard-coded function but decided to postpone deciding what would be the right way of writing it.

I would like to have a data structure that we return which is dynamic (it is aware of the complete list of statuses). Instead of returning a tuple of statuses (under which order is necessary) [2] we can return an instance of the status summary object.

[1] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/mozci.py#L61
[2] return (successful, pending, running, coalesced)

**Comment by go-bears** [comment]
Hello, I thought I would try to tackle the issue you proposed. but I think I created more work for you. Please ignore all the pull requests I just made as they kept failing the travis testing. I'd like to keep trying to work on this, but I'll try to do it from my local machine rather from the web on my friend's machine. I apologize in advance for any inconvenience.

**Comment by armenzg** [comment]
Hey go-bears,
No worries. Does the summary make sense more or less?
I don't actually know what a clean solution will look like so feel free to point to any of your branches.

**Comment by MikeLing** [comment]
Mark this, and I would like to work on this if @go-bears is ok with that.

**Comment by armenzg** [comment]
I'm sorry @go-bears I haven't heard back from you since August. I will be assigning this to @MikeLing 
I hope you understand.

**Comment by MikeLing** [comment]
https://github.com/mozilla/mozilla_ci_tools/pull/431

**Comment by MikeLing** [comment]
close it due to this pr (https://github.com/mozilla/mozilla_ci_tools/pull/431) has been merged :)

**Comment by go-bears** [comment]
Hi Arman,

Thank you for letting  me know.  I was trying to work on it but couldn't
get the code to pass the tox test properly even as a simple dictionary
solution, and was unsure on how to implement the defaultdict().

I started Hackbright Academy's full time program recently, and have been
overwhelmed with homework and learning new technologies. I totally
understand that you re-assigned the fix.  I appreciate the guidance you
gave me. And I'll keep trying.

For the future, how would I ask for guidance about bugs that I have trouble
fixing & would like a code review.  I had started a Mozilla workspace to
test and run the CI tools with tox, but wasn't sure if you or Alice
would've had time to look at and provide specific guidance with the
solution. Now that I have it set up and have tox installed, if i try to fix
another bug would it be ok to ask for coding guidance that way?

Thank so much for the learning opportunity!
Melissa

**Comment by armenzg** [comment]
Hi Melissa,
Congratulations on Hackbright! That is exciting to hear.

One easy way for guidance is to ask directly on the issue and I should be able to get back to you within 24 hours during work days.
Also IRC is a good option.
My apologies if I have failed in the past to get back to you in a timely manner. It's not been easy my projects in the last 4 months.

I'm always happy to help. There's also tons of friendly members in the #ateam channel.
