### ISSUE TITLE
Add a function for clearing cache for BUILDS_CACHE and JOBS_CACHE

### ISSUE THREAD

**Issue by vaibhavmagarwal** [mozilla/mozilla_ci_tools#312]
For consumers of mozci, which are longer running services, we are putting a hack to clear the cache: https://github.com/adusca/pulse_actions/blob/master/pulse_actions/handlers/backfilling.py#L33-L34

We should instead have a function inside mozci and call it directly for such external long running services.

**Comment by armenzg** [comment]
Good idea.

**Comment by armenzg** [comment]
Duped of https://github.com/mozilla/mozilla_ci_tools/issues/273
