### ISSUE TITLE
Add --existing-only support to triggerbyfilters

### ISSUE THREAD

**Issue by adusca** [mozilla/mozilla_ci_tools#332]
Users shouldn't have to manually exclude jobs for which no build is available if they don't want to. Maybe this should be the default behaviour for try (like it used to be with alltalos), idk.

Relevant IRC excerpt:
10:30 <RyanVM|sheriffduty> and -e is optional (but useful)
10:31 <Gijs> can I not use the --existing-only thing ?
10:31 <RyanVM|sheriffduty> dunno
10:31 <Gijs> that would be useful...
10:31 — Gijs doesn't want extra b2g or android things or whatever
10:31 <RyanVM|sheriffduty> I think you'd just filter it down to what you want
10:31 <RyanVM|sheriffduty> so -e "android,b2g" would exclude them

**Comment by armenzg** [comment]
IIUC having it being the default behaviour would be great.

**Comment by xennygrimmato** [comment]
I am working on this issue.

**Comment by xennygrimmato** [comment]
I am trying to run triggerbyfilters.py this way:
`python triggerbyfilters.py mozilla-inbound 80a79987da8b --includes "linux" --dry-run --debug`

@adusca - Since I dont have LDAP credentials, how do I run this?

**Comment by adusca** [comment]
@xennygrimmato Unfortunately, we don't really have a way of testing mozci without LDAP yet, it is the largest barrier for new contributors :-( If you submit a PR I can test your code locally and give you feedback.

For now, can you try creating a file called repositories.txt under ~/.mozilla/mozci
with the following:
```
    {"mozilla-inbound": {
        "repo": "https://hg.mozilla.org/integration/mozilla-inbound",
        "graph_branches": [
            "Mozilla-Inbound"
        ],
        "repo_type": "hg"
    }}
```
(note that this is a 'fake' repositories.txt with just the minimum necessary to see the script running)

Then you can try running with:
```
python triggerbyfilters.py mozilla-inbound 80a79987da8b --includes "linux" --dry-run --debug --query-source=treeherder
```

@armenzg if we gave contributors a version of repositories.txt I believe they would be able to run with--query-source=treeherder --dry-run, but I don't know if that would be bypassing one of Mozilla's access rules.

**Comment by vaibhavmagarwal** [comment]
Since repositories.txt is a read only file, I think there will be no harm in removing the need for LDAP credentials at the source level for it, or host it on another url. Do you guys think that can be done?

**Comment by armenzg** [comment]
I could host it at people.mozilla.com until then. Should we go that way or fix https://github.com/mozilla/mozilla_ci_tools/issues/347?

We could also commit in the repo. We don't really repositories that often.

**Comment by vaibhavmagarwal** [comment]
In an ideal world, it would make sense to just remove the need for LDAP credentials at repositories.txt [1]. However if that is not possible, I am fine with committing a static file in the repository for ease of use to new contributors.


[1] - https://secure.pub.build.mozilla.org/buildapi/self-serve/branches

**Comment by xennygrimmato** [comment]
@adusca - I created repositories.txt as you suggested. On running `python triggerbyfilters.py mozilla-inbound 80a79987da8b --includes "linux" --dry-run --debug --query-source=treeherder`, I got the following response:

`No handlers could be found for logger "mozci"`

**Comment by armenzg** [comment]
I believe this was fixed in here:
https://github.com/mozilla/mozilla_ci_tools/commit/d5d914ee98c53ecffae4577577b168722a57a10e
