### ISSUE TITLE
Release the buildapi module as a Python package and depend on it

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#343]
This is filed in here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1203618

**Comment by adusca** [comment]
@F3real, thanks for your interest in this issue! This is also being tracked on bugzilla, under the bug 
https://bugzilla.mozilla.org/show_bug.cgi?id=1203618

You would have to submit a patch to buildapi [1] with a new file (called buildapi_client.py) containing the functions in builapi.py and after that gets merged you should submit a patch to mozci to remove the functions here and import the ones from upstream instead. We want to do this because we believe this functions would be useful for other modules besides mozci, and we want to make them more easily accessible.

Steps:

-   create an account at bugzilla
-    clone buildapi
-   write a patch with the new file containing the functions (there are instructions on how to create a patch with mercurial here: https://ateam-bootcamp.readthedocs.org/en/latest/guide/development_process.html#mercurial )
- submit your patch on bug 1203618 and ask for review (probably from :armenzg or :coop)

[1] http://hg.mozilla.org/build/buildapi/file/tip/buildapi

**Comment by F3real** [comment]
I have few questions. First in which directory should I create buildapi_client.py. Second buildapi.py imports some things from mozci. Should I import those things to in buildapi_client.py ? I added errors to buildapi_client.py already but that's probably not best solution.

**Comment by armenzg** [comment]
Hi @F3real that is a very good question!

Please bear with me as I think this can be a bit cumbersome.

First, I believe we should start with a fork of the buildapi repo either on GitHub or BitBucket (whatever is easier for you). That way I can checkout your code and test it out.

Second, the logic about repositories could be moved to mozci/mozci.py Since we're moving that logic out of buildapi.py we won't need the VALIDATE and pushlog functionality.
I think we will need the 3 lines after https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L237

Third, with regards to logging, let's use logging.getLogger("buildapi_client").

Fourth, with regards to authentication, change the signatures of the function to need an extra parameter auth. That way we won't need the auth functionality of mozci.
When we switch to using such package we will make mozci be responsible to pass auth approprietately.

Fifth, bring with us the BuildapiError and rename AuthenticationError to BuildapiAuthError.

And last, please don't release the package to pypi until we're closer to end of the line.
That way we can get naming and versioning right. I want us to follow semver. We can talk about it when the times comes :)

That's all I can think of at the moment! Thanks for your understanding.

**Comment by F3real** [comment]
I haven't really understood what should I do with 3 lines you talked about. After removing all logic about repositories it seems BuildapiError is not needed too so should he be removed ? I did some progress
https://github.com/F3real/build-buildapi/blob/master/buildapi/lib/buildapi_client.py#L74

**Comment by armenzg** [comment]
Hi @F3real this is looking in the right direction.

Could you please move the file under the root directory as buildapi_client/buildapi_client.py?
Could you also add what is needed to create a python package?

I think you can start making related changes to youe mozci fork where we remove buildapi.py and we include a buildapi_client python package as a dependency.

WRT to the 3 lines (more like ) you will need this piece of code:

    def query_repositories():
          url = "%s/branches?format=json" % HOST_ROOT
          LOG.debug("About to fetch %s" % url)
          req = requests.get(url, auth=get_credentials())
          if req.status_code == 401:
              raise BuildapiAuthError("Your credentials were invalid. Please try again.")

You will need the code that I mentioned that should be moved to mozci/mozci.py to call this method.

Here's the comparison:
https://github.com/mozilla/build-buildapi/compare/master...F3real:master

**Comment by F3real** [comment]
Hey, I've got few questions.
I am not sure if I should modify setup.py in root dir or create another one (not sure if there can be 2 in project). I have created new function from piece of code u said we need (https://github.com/F3real/build-buildapi/blob/master/buildapi_client/buildapi_client.py). I've also seen that we need to specify license for project when publishing and I am not sure which license if buildapi.

**Comment by armenzg** [comment]
Hi @F3real there can be two different setup.py file on a repo.
Having a buildapi_client/ directory allows you to have a logical separation from the rest of the project.

The diff looks good. Once you add the setup.py and the packaging works you should start modifying mozci to start using this. Since you don't have credentials to access Buildapi. I will test it for you once you have the changes ready.

It will also be nice to bring forth the buildapi tests:
https://github.com/mozilla/mozilla_ci_tools/blob/master/test/test_buildapi.py

Probably @adusca can give you some pointers as to how to run the tests under your new repo. I really suck at unit testing.

**Comment by armenzg** [comment]
Hi @F3real, I've asked for the main developers of buildapi to use a distinct repo.
Would you mind forking this and using it for this?
https://github.com/armenzg/buildapi_client

So far the code looks good. I will start writing a python notebook to help test your code changes.

**Comment by armenzg** [comment]
I've noticed these changes are required [1]

I've also commited a python notebook which helps me test your changes [2].
With the argument dry_run=True you can tested these changes without authentication.

To use the notebook:
1) create a virtualenv and activate it
2) install your client (python setup.py develop); it installs requests
3) install jupyter
4) optional packages (keyring if you had credentials to store in it)
5) start it up with "ipython notebook" (within the virtualenv)

[1]
diff --git a/buildapi_client/buildapi_client.py b/buildapi_client/buildapi_client.py
index d0dc9cf..6a98f2a 100644
--- a/buildapi_client/buildapi_client.py
+++ b/buildapi_client/buildapi_client.py
@@ -9,7 +9,6 @@ https://secure.pub.build.mozilla.org/buildapi/self-serve
 The docs can be found in here:
 http://moz-releng-buildapi.readthedocs.org
 """
-from __future__ import absolute_import
 import json
 import logging
 import os
@@ -153,4 +152,4 @@ def make_query_repositories_request(auth):
     req = requests.get(url, auth=auth)
     if req.status_code == 401:
         raise BuildapiAuthError("Your credentials were invalid. Please try again.")
-    return req
+    return req.json()

[2] https://github.com/armenzg/buildapi_client/blob/master/notebooks/Test%20buildapi%20methods.ipynb

**Comment by F3real** [comment]
Hey @armenzg ,
I've added and fixed tests. I was wondering should BuildapiAuthError be exported too in init.py. Anyway could you take look at code and see if it's alright? 
I'll start modifying mozci soon.

**Comment by armenzg** [comment]
Hi @F3real now that we have a PR for this, let's use it for further discussions:
https://github.com/armenzg/buildapi_client/pull/1

I will answer there.

**Comment by armenzg** [comment]
Fixed!

**Comment by armenzg** [comment]
https://github.com/mozilla/mozilla_ci_tools/pull/381
