### ISSUE TITLE
Add TaskCluster GitHub integration to Mozci

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#345]
Let's try using it to support the project + seeing what benefits we get compared to TravisCI.
http://linuxpoetry.com/blog/section/mozilla/24

**Comment by armenzg** [comment]
Also on Air.m.o:
https://air.mozilla.org/taskcluster-github-continuous-integration-for-mozillians-by-mozillians-2/

**Comment by xennygrimmato** [comment]
I discussed this with @MikeLing and I would like to work on this.
First, should I emulate what TravisCI is currently doing with TaskCluster-Github, and meanwhile take inputs from @armenzg and @adusca  regarding what else we could add to it?

**Comment by armenzg** [comment]
Some more information in this thread:
https://groups.google.com/forum/#!topic/mozilla.tools.taskcluster/dP0CBiWiSMU

**Comment by armenzg** [comment]
Hi @xennygrimato have you made progress in this? or is it fine if we close it?

**Comment by armenzg** [comment]
We can live without this.
