### ISSUE TITLE
Add the ability in mozci scripts to re-trigger all existing jobs / all failed jobs for a particular revision

### ISSUE THREAD

**Issue by vaibhavmagarwal** [mozilla/mozilla_ci_tools#346]
This feature was requested by @jgraham.

**Comment by armenzg** [comment]
I believe this can be accomplished through TH. I would not want this implemented if already have a solution for it.

**Comment by vaibhavmagarwal** [comment]
Today :ato also asked for this feature for failing jobs. I think we should give this functionality to users, as the current treeherder way is a bit time consuming.

**Comment by armenzg** [comment]
Do you think we should also make it a Treeherder action?

On 16 September 2015 at 14:28, Vaibhav Agrawal <notifications@github.com>
wrote:

> Today :ato also asked for this feature for failing jobs. I think we should
> give this functionality to users, as the current treeherder way is a bit
> time consuming.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armenzg/mozilla_ci_tools/issues/346#issuecomment-140833655>
> .
>



-- 
Zambrano Gasparnian, Armen
Automation & Tools Engineer
http://armenzg.blogspot.ca

**Comment by vaibhavmagarwal** [comment]
Not sure. Will need to see if it is actually used that frequently or not to take space in the ever increasing TH UI :)

**Comment by armenzg** [comment]
Good point. Let's wait for customers to speak up! :)

On 16 September 2015 at 17:04, Vaibhav Agrawal <notifications@github.com>
wrote:

> Not sure. Will need to see if it is actually used that frequently or not
> to take space in the ever increasing TH UI :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armenzg/mozilla_ci_tools/issues/346#issuecomment-140893907>
> .
>



-- 
Zambrano Gasparnian, Armen
Automation & Tools Engineer
http://armenzg.blogspot.ca

**Comment by armenzg** [comment]
@MikeLing I believe this is an issue that you have the skills to fix. We could add it as a mode to the trigger.py script. Please let me know if you're interested on working on this.

**Comment by MikeLing** [comment]
yes of course, I would happy to work on that :)

**Comment by armenzg** [comment]
Thank you MikeLing!

**Comment by armenzg** [comment]
Hi @MikeLing as you asked on IRC.

I would suggest you writing a temporary script trying to use this query source [1]
Point it to a push and try to investigate which jobs are green and which ones are not.

You should be able to find examples in the repo where we use that class.
If you get stuck, please post a gist of the script you're writing and we can discuss it.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/5a93658ebd7a2713f3a51493775c56c24436e358/mozci/query_jobs.py#L215

**Comment by MikeLing** [comment]
@armenzg Is that mean something like this? https://gist.github.com/MikeLing/4f6a1c54e9177c8a39b9
and we can trigger it separately :)

**Comment by armenzg** [comment]
OK good!
You're in the right direction.
Now that you have a piece of code that works, I would carefully integrate it as part of trigger.py (a new mode).

**Comment by MikeLing** [comment]
> I would carefully integrate it as part of trigger.py (a new mode).

yes indeed. I think integrate it as a new mode for trigger.py is a good ideal :)

**Comment by MikeLing** [comment]
https://github.com/mozilla/mozilla_ci_tools/pull/433

**Comment by armenzg** [comment]
Fixed by @MikeLing
