### ISSUE TITLE
Retrieve repository meta-data somewhere different than buildapi (to remove the need for LDAP credentials)

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#347]
Once we fix issue #344 we will have informaiton about repositories which already is part of the repository version-control-tools.

(ci_tools)MacAir ci_tools git:[mozci_bbb] $ python ~/repos/ci_tools/mozci/scripts/misc/buildbot_to_taskcluster.py --repo-name try --revision 88ba41c28dce -g "{'Linux x86-64 try build': ['Ubuntu VM 12.04 x64 try opt test mochitest-1']}" --dry-run --debug
09/22/2015 08:28:13 root INFO:	 Setting DEBUG level
09/22/2015 08:28:13 mozci DEBUG:	 Determine repository associated to try
09/22/2015 08:28:13 mozci DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/branches?format=json
Please enter your full LDAP email address:

**Comment by armenzg** [comment]
We can determine this information from the treeherder client:
In [4]: tc.get_repositories()
Out[4]: 
[{u'active_status': u'active',
  u'codebase': u'gecko',
  u'description': u'',
  u'dvcs_type': u'hg',
  u'id': 1,
  u'name': u'mozilla-central',
  u'repository_group': {u'description': u'', u'name': u'development'},
  u'url': u'https://hg.mozilla.org/mozilla-central'},

**Comment by armenzg** [comment]
We could also have this information be part of a pushlog client once it is moved to version-control-tools.

https://bugzilla.mozilla.org/show_bug.cgi?id=1203621
https://hg.mozilla.org/hgcustom/version-control-tools

**Comment by armenzg** [comment]
From reading the bug, we can have under pylib/mozpushlogclient the file repository.py [1] + our pushlog.py module.

[1] https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/pylib/mozautomation/mozautomation/repository.py

**Comment by xennygrimmato** [comment]
Can you assign me to this issue?

**Comment by vaibhavmagarwal** [comment]
@xennygrimmato this will involve (most-likely) the repositories.txt file from LDAP to the repository. Do you have access to it?

**Comment by xennygrimmato** [comment]
I have a copy of repositories.txt, given to me by @adusca on my local
machine. I do not have LDAP access.

On Sunday, November 22, 2015, Vaibhav Agrawal <notifications@github.com>
wrote:

> @xennygrimmato <https://github.com/xennygrimmato> this will involve
> (most-likely) the repositories.txt file from LDAP to the repository. Do you
> have access to it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozilla_ci_tools/issues/347#issuecomment-158764314>
> .
>


-- 
Regards,
Vaibhav Tulsyan.

**Comment by vaibhavmagarwal** [comment]
Cool, then go ahead, commit it, make the necessary changes to code and send a PR!
Assigning you this issue.

**Comment by armenzg** [comment]
The pushlog_client code has now landed:
https://hg.mozilla.org/hgcustom/version-control-tools/rev/6021c9031bc3

We can talk to gps on how to make use of repository.py for this:
https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/pylib/mozautomation/mozautomation/repository.py

I would prefer fixing it this way since others could use pushlog_client to deal with repositories meta-data.

**Comment by xennygrimmato** [comment]
Can you give me some clarity on how pushlog_client can be used for providing repositories.txt data?

**Comment by armenzg** [comment]
repository.py has metadata about valid repositories.
It would need a bit of manipulation and might need moving the location of repository within that repo.

**Comment by armenzg** [comment]
@xennygrimmato Is it OK if we allow someone else pick it up?

**Comment by xennygrimmato** [comment]
Yup

On Friday, February 19, 2016, Armen Zambrano <notifications@github.com>
wrote:

> @xennygrimmato <https://github.com/xennygrimmato> Is it OK if we allow
> someone else pick it up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozilla_ci_tools/issues/347#issuecomment-186349107>
> .
>


-- 
Regards,
Vaibhav Tulsyan.

**Comment by armenzg** [comment]
Thank you!

**Comment by armenzg** [comment]
Fixed with https://github.com/mozilla/mozilla_ci_tools/pull/438
