### ISSUE TITLE
Create script which generates .yml files under Mozilla's Gecko tree

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#361]
Recently we have added the ability to create TaskCluster graphs and each task (json objects) which represent a job on Buildbot. Run command [1] to see what a graph looks like.
The code that generates the tasks is here [2] and here [3].

In TaskCluster's decision task [4] we take information from .yml files and turn it into a TC graph in the same format as mozci.

If we had a script that instead of generating a graph it would generate the necessary .yml it would be great. This would be useful if we want to run a Mac build generated on TC but run it against the Buildbot builders.

In [5], we can see the .yml file of a FX build which inherits from [6]

We would need to generate the following files:
* testing/taskcluster/tasks/buildbot_bridge_tests.yml
* testing/taskcluster/tasks/buildbot_bridge_tasks/{suitename}_{opt,debug}.yml

The script should probably follow this:
> python mozci/scripts/my_script.py --children-of "OS X 10.7 64-bit try leak test build"

[1]
> python ~/repos/ci_tools/mozci/scripts/buildbot_to_taskcluster.py --repo-name try \
> --revision 4e195f44cd83 --trigger-from-task-id J05EWiFLTcmCqBYxSPbJ6g \
> --children-of "OS X 10.7 64-bit try leak test build" --dry-run
[2] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildbot_bridge.py#L61
[3] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/tc.py#L97
[4] 
[5] https://hg.mozilla.org/projects/alder/file/f186f43db1fd/testing/taskcluster/tasks/buildbot_bridge_build/linux32_firefox_debug.yml
[6] https://hg.mozilla.org/projects/alder/file/f186f43db1fd/testing/taskcluster/tasks/buildbot_bridge_build.yml

**Comment by armenzg** [comment]
This push https://hg.mozilla.org/try/rev/52bcfd8df0a1 only has Buildbot jobs
In this push https://hg.mozilla.org/try/rev/1c68092b1972 I'm trying to add more and more .yml files until I can run the same number of jobs as the Buildbot ones.
The .yml files which you see on that push are for *non* Buildbot jobs so they have many more fields

**Comment by armenzg** [comment]
Link to gecko decision tasks: https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&filter-searchStr=gecko

**Comment by MikeLing** [comment]
Hi @armenzg , this issue seems very interesting and I would like to learn more about how we use taskCluster inside. So, could you assign this to me? :)

**Comment by armenzg** [comment]
Thank you MikeLing! This would be *very* useful to have as it will make our lives easier.

**Comment by armenzg** [comment]
Here are some more notes. Please read them. It will help you understand what you're helping with:
http://armenzg.blogspot.ca/2015/09/mozilla-ci-tools-upcoming-support-for.html
http://hearsum.ca/blog/buildbot-taskcluster-bridge-an-overview.html

**Comment by armenzg** [comment]
Hi @MikeLing have you had a chance to make progress in here?

**Comment by MikeLing** [comment]
hey @armenzg , I haven't get some progress. :(

**Comment by armenzg** [comment]
Do you want me to make unassigned for now and have it available for either you or someone that comes along that can focus on it?

**Comment by MikeLing** [comment]
ok, Let's unassigned it from me for now and I will commit a PR directly if nobody work on it at that time :)

**Comment by armenzg** [comment]
We can live without this.
