### ISSUE TITLE
Periodically clean allthethings.json in-memory cache

### ISSUE THREAD

**Issue by adusca** [mozilla/mozilla_ci_tools#365]
To insure that pulse_actions doesn't act on old information.

**Comment by armenzg** [comment]
I already landed some code disable_validations() in one of my branches:
https://github.com/mozilla/pulse_actions/compare/master...armenzg:bug1180732_improve_backfilling

**Comment by armenzg** [comment]
That code landed.
From my findings, there's no way to have an up-to-date allthethings.json provided by releng.
