### ISSUE TITLE
Give SETA awareness to mozci

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#366]
Whenever we fetch a new allthethings.json we should also determine the schedule at which SETA runs.
This is useful for automatic backfilling since we want to know how far we need to go to find an issue.

For instance, our current SETA skipping level is of 7 pushes instead of 5 pushes [1]
The information is contained within the scheduler's name:
    "tests-fx-team-snowleopard-opt-unittest-7-3600":

For now, the same value is used across trees.

[1] https://github.com/mozilla/pulse_actions/blob/master/pulse_actions/handlers/backfilling.py#L25

**Comment by F3real** [comment]
I am interested in working on this.
