### ISSUE TITLE
Make mozci aware of pending load

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#373]
Some sources of knowledge:
https://bug1204970.bmoattachments.org/attachment.cgi?id=8680680
https://bugzilla.mozilla.org/show_bug.cgi?id=1204970

**Comment by armenzg** [comment]
Some code already landed in here:
https://github.com/mozilla/mozilla_ci_tools/compare/master...armenzg:bug1195851_pending_jobs

Here's the bug where this would be used in:
https://bugzilla.mozilla.org/show_bug.cgi?id=1195851

**Comment by armenzg** [comment]
I moved part of the patches in that branch to the buildapi_client repo (since we've moved it):
https://github.com/armenzg/buildapi_client/tree/bug1195851_pending_jobs

**Comment by F3real** [comment]
I am interesting in trying to do this.

**Comment by armenzg** [comment]
Thanks Stefan!

**Comment by armenzg** [comment]
Let me know if you have trouble using the branch in my repo.

**Comment by armenzg** [comment]
We won't be using this for a while.
Let's close it and re-open it if it comes to it:
https://github.com/armenzg/buildapi_client/commit/ae51e9ebd702e16fcf2b34bdc74ec4aa88fedf74
