### ISSUE TITLE
Remove bugsy as a dependency to mozci

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#375]
@vaibhavmagarwal I would like to remove generate_triggercli.py and bugsy from mozci as it is not necessary needed to support a specific functionality of mozci.

Does this work for you?

I'm also considering removing some of the other scripts of mozci. Not sure yet. I will write more about it when I have a plan.

**Comment by vaibhavmagarwal** [comment]
Sure, generate_triggercli.py was more of a hack to test if it helped to deal with intermittent oranges. I think it is no longer useful.

**Comment by armenzg** [comment]
Thanks @vaibhavmagarwal !

**Comment by adusca** [comment]
I think this is a good bug for a new contributor.

**Comment by vaibhavmagarwal** [comment]
I don't think this is a good first bug. Removing an unused file does not
add value to knowing about the project, in fact causes confusion (I know
:mikeling was confused since scripts were not working under misc/
directory).

**Comment by vaibhavmagarwal** [comment]
Looks like @armenzg has fixed this issue in https://github.com/mozilla/mozilla_ci_tools/commit/88d592b119fbbd41a9e55076a763b62f1c571479. Closing this.

**Comment by armenzg** [comment]
I think it would have been a good issue as one first step with a project is to get the feet wet with GitHub and the most minimal contribution process but I was already on it :) It's easy to forget our first time dealing with GH, forks and everything around a PR!
