### ISSUE TITLE
Running triggerbyfilters.py with wrong LDAP credentials gives a logging error

### ISSUE THREAD

**Issue by xennygrimmato** [mozilla/mozilla_ci_tools#379]
I am running:
`python triggerbyfilters.py mozilla-inbound 80a79987da8b --includes "linux" --dry-run --debug --query-source=treeherder`
I am passing invalid/wrong LDAP credentials and getting this:
`No handlers could be found for logger "mozci"`
Stack trace: https://pastebin.mozilla.org/8852391

**Comment by vaibhavmagarwal** [comment]
This issue is reproducible. @xennygrimmato showed interest in solving the bug.

**Comment by armenzg** [comment]
Thanks @xennygrimmato for reporting this! Let me know if you need any pointers.

**Comment by armenzg** [comment]
Tagging as part of the "user facing" milestone.

**Comment by xennygrimmato** [comment]
For this issue, should I commit `repositories.txt` inside:
https://github.com/armenzg/buildapi_client

and in this function:
https://github.com/armenzg/buildapi_client/blob/master/buildapi_client/buildapi_client.py#L115
I must fetch data from the same repositories.txt file. Is that the right direction to think?

**Comment by vaibhavmagarwal** [comment]
I think that is the right direction. @armenzg does this sound good to you?

**Comment by armenzg** [comment]
triggerbyfilters.py has merged with trigger.py.
I would prefer seeing metadata about repositories being determined through treeherder or the pushlog_client (issue #347).
Closing this for now.

My apologies for having missed the last comment.
