### ISSUE TITLE
Merge triggerbyfilters.py with trigger.py

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#383]
It would also be good if we could have "commands" for trigger.py for everyone of the modes in which we can run.

If you do `git help` you will you that there are various commands.
Each of those commands can have their own set of optional arguments.

For instance, if we considered `filter` a mode or command, we could have:
trigger.py filter --help
and that would show the optional arguments which are specific to triggering with filters.

**Comment by MikeLing** [comment]
Hi @adusca and @armenzg , I had do some initial work for this issue. Hope it's ok :)
https://github.com/mozilla/mozilla_ci_tools/pull/402

**Comment by armenzg** [comment]
Done done!
