### ISSUE TITLE
Make trigger.py to schedule jobs through TaskCluster instead of Buildapi

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#384]
trigger.py [1] currently schedules jobs through Buildapi instead of TaskCluster.
We can switch this by scheduling through the classes defined in mozci/ci_manager.py
Technologically, we want to move away from using Buildapi directly since it will be deprecated eventually.

I want to allow people to say --scheduling-source 'buildapi' if they want to but default to TaskCluster.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/scripts/trigger.py
[2] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/ci_manager.py

**Comment by MikeLing** [comment]
Hi @armenzg , do you want me to work on this? I'm interesting in this, so you could assign it to me if it's OK: )

**Comment by MikeLing** [comment]
Is that the BuildApi you mean in here (https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/scripts/trigger.py#L18)? which defined in query_job? I only find this part is related with BuildApi, is that correct?

**Comment by adusca** [comment]
@MikeLing Right now we do all of our trigger requests (trigger_arbitrary_job, make_retrigger_request) using [BuildApi self-serve](https://secure.pub.build.mozilla.org/buildapi/self-serve). 

We would like to use BBB (Buildbot Bridge) instead. [This](https://github.com/mozilla/pulse_actions/blob/master/pulse_actions/handlers/treeherder_runnable.py#L63) is an example of using BBB to schedule a graph of builders.

**Comment by adusca** [comment]
@armenzg Since using BBB requires different credentials, how would current mozci users be able to continue using trigger.py?

**Comment by armenzg** [comment]
I added some info on how to get credentials in here:
http://mozilla-ci-tools.readthedocs.org/en/latest/buildbot_bridge.html

Do you think this is a good start?

**Comment by adusca** [comment]
@armenzg Would this break trigger.py for our users unless they specify --buildapi? Or it is safe to assume that most of our users will have TC credentials?

**Comment by armenzg** [comment]
It will be fine until we make a release.
We should give people heads up and tell them ahead of time that they should get TC credentials.

**Comment by MikeLing** [comment]
I think this issue could be closed for this PR(https://github.com/mozilla/mozilla_ci_tools/pull/390) had been merged :)
