### ISSUE TITLE
Use retries instead of reruns

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#386]
jonasfj, says that reruns is an anti-pattern and we should use retries instead
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/tc.py#L114
http://docs.taskcluster.net/queue/api-docs/#createTask

Please read the docs and ask jonasfj to help us understand the reason of the switch since I can't remember at the moment.

**Comment by xennygrimmato** [comment]
Can this be closed now?

**Comment by vaibhavmagarwal** [comment]
@xennygrimmato is this no longer a valid issue? Could you please comment here the reason for it?

**Comment by xennygrimmato** [comment]
After a discussion with @jonasfj and @armenzg it was concluded that we do not need to modify the current behaviour. The discussion thread is on our personal emails, so if you want, I can share it with you.

**Comment by armenzg** [comment]
Yes, please.
Could you please add the convo with jonasfj?
That way it becomes publicly available.

Thanks!

On 24 November 2015 at 09:11, Vaibhav Tulsyan <notifications@github.com>
wrote:

> After a discussion with @jonasfj <https://github.com/jonasfj> and @armenzg
> <https://github.com/armenzg> it was concluded that we do not need to
> modify the current behaviour. The discussion thread is on our personal
> emails, so if you want, I can share it with you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozilla_ci_tools/issues/386#issuecomment-159278162>
> .
>



-- 
Zambrano Gasparnian, Armen
Automation & Tools Engineer
http://armenzg.blogspot.ca

**Comment by armenzg** [comment]
From Jonas:
I think that is totally sane!

Sorry, if I some time say crazy things like reruns are bad -- which they are (sort of like drugs - really hard to get off, once hooked, hehe).
I'm not sure how much reruns we actually use in-tree. So maybe it's not so bad.
Either way I don't think it's a problem that mozci needs to do anything about. As long as it doesn't worsen the problem, which is
not the case when you default reruns to zero.

--
Regards Jonas Finnemann Jensen.

2015-11-23 10:22 GMT-08:00 Armen Zambrano Gasparnian <armenzg@mozilla.com>:

    Ah!

    In our case we set rerun to 0 if not defined and retries to 5 if not defined:
    https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/tc.py#L111

    Do you think that is a fine approach? Or should we change anything?

    At the moment, these are the tasks used to schedule Buildbot jobs via the Buildbot Bridge.

    regards,
    Armen


    On 23 November 2015 at 12:38, Jonas Finnemann Jensen <jojensen@mozilla.com> wrote:

        Maybe we need to loop armen in :)

        If it is regarding automatic reruns... as done by the task-graph scheduler...

        @armenzg,
        I'm not sure what the issue is here. When I say reruns are bad, and that we should only do retries, it's probably an attempt at saying that automatically reruning stuff as a way to deal with intermittent tests is bad, and hence, we should stop doing that.
        In automation testing I would seem to think that retrying intermittent tests is really an anti-pattern.

        But I don't think this is solved at mozci level.. or solved as a small bug.
