### ISSUE TITLE
Upgrade requests to the latest release

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#391]
From gps:
requests 2.6.0 contains a CVE fix. And the latest version has an updated cert bundle. For security reasons, please require the newest released requests package, which is currently 2.8.1.

**Comment by MikeLing** [comment]
https://github.com/mozilla/mozilla_ci_tools/pull/425

**Comment by MikeLing** [comment]
I think this issue could been closed https://github.com/mozilla/mozilla_ci_tools/pull/425 since this PR has been merged :)
