### ISSUE TITLE
Add determine_missing_jobs() to BaseCIManager

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#392]
I want to have a generic function which both BuildAPIManager and TaskClusterBuilapiManager can use to implement trigger_missing_jobs.

If you look at https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L504
we don't try to see which jobs are missing.
We simply make calls to trigger_range() for every job which is slow.

Instead we should:
* determine all buildbot jobs that could be triggered (e.g. list_builders)
* determine which jobs are run for a revision
* determine what is missing from the previous two sets
* return that

Once we have this function in BaseCIManager, we should write a new trigger_missing_jobs() from mozci.py to BuildAPIManager and make use of determine_missing_jobs.

**Comment by armenzg** [comment]
query_source.py seems a better place.

**Comment by MikeLing** [comment]
hi @armenzg , I would like to work on this issue: )

**Comment by armenzg** [comment]
Hi @MikeLing, @F3real already has some progress in this area.

Could you please focus on https://github.com/mozilla/mozilla_ci_tools/issues/393 or another issue?

**Comment by adusca** [comment]
Fixed in #388
