### ISSUE TITLE
Add determine_range() to query_jobs.py

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#393]
In trigger_range() [1] from mozci.py, we try to determine what to schedule and iterate through it.
Instead, we should create a determine_range() function in BaseCIManager that should not schedule anything but yield for each revision what jobs need to be scheduled.

Once that is in place, we should write trigger_range() in BuildapiManager to make use of it.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L414

**Comment by armenzg** [comment]
query_source.py

**Comment by armenzg** [comment]
query_jobs.py

**Comment by MikeLing** [comment]
Hmm, do we still need this issue? Actually, I haven't found determine_range() function in BaseCIManager. @adusca and @armenzg

**Comment by armenzg** [comment]
I will leave this issue unread in my inbox and look at it on Monday.
I need to revisit this.

**Comment by armenzg** [comment]
Let's close this for now.
