### ISSUE TITLE
determine_missing_jobs finds both opt and pgo jobs if available

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#395]
Once https://github.com/mozilla/mozilla_ci_tools/pull/388 wraps up.

In some repositories like mozilla-inbound, we trigger "OPTimized" jobs on developer's pushes while we trigger "pgo" jobs on a schedule.

We should allow passing a parameter to determine_missing_jobs to:
* return only opt jobs (when there is equivalent pgo jobs) - by default
* return only pgo jobs (when there is equivalent opt jobs)
* return both type jobs

This is not a priority type of work.

**Comment by armenzg** [comment]
@MikeLing I believe you did *not* have your eye on this issue; correct me if I'm wrong.
@tapeshmandal is interested on working on this.

**Comment by mandaltapesh** [comment]
@armenzg i think this is the function that deals with the above mozci/query_jobs.py
line 45 

 def determine_missing_jobs(self, repo_name, revision, considered_list_of_builders=None):
        if considered_list_of_builders is None:
            considered_list_of_builders = list_builders(repo_name=repo_name)
        considered_list_of_builders = set(considered_list_of_builders)
        coalesced_jobs = self._select_jobs_with_specified_status(
            repo_name=repo_name,
            revision=revision,
            status=COALESCED,
            considered_list_of_builders=considered_list_of_builders)

        missing_jobs = self._select_missing_jobs(
            repo_name=repo_name,
            revision=revision,
            considered_list_of_builders=considered_list_of_builders)
        return missing_jobs + coalesced_jobs

could you please suggest as to which path to follow :)

**Comment by armenzg** [comment]
Hi @tapeshmandal , you should look into starting a python notebook (here's an example [1]).
If you manage to understand and use Python notebooks for development you will gain a very good skill for your career. It takes a bit to get used it (logging and reloading modules) but it is a great tool.

In it, you can import this function and call it with 'mozilla-inbound' as the repo_name.
Pick a revision without a PGO build; see URL [2]. In other words, I want you to see all missing jobs from a push and see if the pgo builders are showing up or not.

This will be a bit of a though issue but I think it will help you grow if you can stick with it.

You can focus for instance on 'Linux x86-64 mozilla-inbound build' and 'Linux x86-64 mozilla-inbound pgo-build'. One is an optimized build and the other one a PGO build.
In certain repositories we don't have both.
In repositories like m-i, we want to give determine_trigger_objective() the ability of not returning the PGO builders.
If there is both type of builds, we want to return the opt one.

Also read the comment from Alice https://github.com/mozilla/mozilla_ci_tools/pull/388#issuecomment-159674728

There's also in here a function that deals with something similar [3]
and this one [4]. Specially the last one.

[1] https://github.com/armenzg/pulse_actions/blob/rebuild_tc_jobs/notebooks/Appending%20more%20jobs%20to%20pushes%20with%20--rebuild.ipynb
[2] https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&filter-searchStr=PGO
[3] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/platforms.py#L366
[4] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/platforms.py#L490

**Comment by armenzg** [comment]
We will need to either modify that test and MOCK_ALLTHETHINGS https://github.com/mozilla/mozilla_ci_tools/blob/master/test/test_platforms.py#L176

**Comment by armenzg** [comment]
What this issue is about to change the result of this to only two builders:
```python
In [15]: sorted([x for x in list_builders(repo_name='mozilla-inbound', filter=True) if x.startswith(u'Windows XP 32-bit mozilla-inbound') and str(x).endswith('xpcshell')])
Out[15]: 
[u'Windows XP 32-bit mozilla-inbound debug test xpcshell',
 u'Windows XP 32-bit mozilla-inbound opt test xpcshell',
 u'Windows XP 32-bit mozilla-inbound pgo test xpcshell']
```

**Comment by armenzg** [comment]
This got fixed in here:
https://github.com/mozilla/mozilla_ci_tools/commit/060e7b4948108d324521e7ba7382f6802bba6e46
