### ISSUE TITLE
Switch mozci to using pushlog_client

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#396]
@MikeLing helped us release the pushlog module as its own python package.
We should start making use of it.

**Comment by MikeLing** [comment]
Hey, I would like to work on this job. Just want to make my job more continuity ；）

**Comment by armenzg** [comment]
Thank you @MikeLing !

**Comment by armenzg** [comment]
Accomplished by @MikeLing !! \o/

**Comment by armenzg** [comment]
https://github.com/mozilla/mozilla_ci_tools/commit/eb5866acfface273b521570b2f695c270a878455
