### ISSUE TITLE
[Tracker] Have all the functions we call in trigger.py in both BuildApiManager and TaskClusterBuildbotManager

### ISSUE THREAD

**Issue by adusca** [mozilla/mozilla_ci_tools#397]
This blocks #384 

The goal is, in the future, to be able to do:
```
ci_manager = TaskClusterBuildbotManager() or BuildApiManager()
```
in trigger.py, depending on what the user chooses, and then we can call every function in every mode as:
```
ci_manager.function()
```
We will need to move the exisiting mozci.py functions to BuildApiManager() and write equivalent functions (with the same API) on TaskClusterBuildbotManager()
- [x] trigger_range
- [x] trigger_missing_jobs (check PR #388)
- [ ] make_retrigger_request (might be impossible, we need to think about this one)

Note that determine_revlist doesn't need to be adapted for this.

**Comment by armenzg** [comment]
\o/

**Comment by armenzg** [comment]
@MikeLing did a wonderful work and got this done. Thanks!
