### ISSUE TITLE
Support trigger_build_if_missing on trigger_missing_jobs in BBB

### ISSUE THREAD

**Issue by adusca** [mozilla/mozilla_ci_tools#398]
Currently, trigger_missing_jobs_for_revision on BBB takes trigger_build_if_missing as a parameter [1], but it doesn't do anything with it. We need to pass the argument to buildbot_graph_builder. There we need to add an extra if clause to only add the build job and the test job if trigger_build_if_missing is False [2]

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/ci_manager.py#L182
[2] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/buildbot_bridge.py#L166

**Comment by armenzg** [comment]
Once I resume work in April around TC I will see what is actually needed.
The code has changed a bit since November
