### ISSUE TITLE
"That repository does not exist." is reported if --repo-name is not specified explicitly

### ISSUE THREAD

**Issue by upsuper** [mozilla/mozilla_ci_tools#410]
It seems to me a while before, mozci was able to deduce the repo name itself without specifying anything. But after I upgraded to the latest version today, when I tried to run `mozci-trigger -b "Ubuntu VM 12.04 try opt test mochitest-e10s-browser-chrome-2" -r 18ecc556cb92`, it reports
```text
Traceback (most recent call last):
  File "/usr/local/bin/mozci-trigger", line 9, in <module>
    load_entry_point('mozci==0.23.2', 'console_scripts', 'mozci-trigger')()
  File "/usr/local/lib/python2.7/site-packages/mozci/scripts/trigger.py", line 237, in main
    repo_url = query_repo_url(options.repo_name)
  File "/usr/local/lib/python2.7/site-packages/mozci/repositories.py", line 41, in query_repo_url
    return query_repository(repo_name)["repo"]
  File "/usr/local/lib/python2.7/site-packages/mozci/repositories.py", line 34, in query_repository
    raise MozciError("That repository does not exist.")
mozci.errors.MozciError: That repository does not exist.
```

It only worked after I appended `--repo-name try` to the argument list.

This behavior doesn't make sense to me, because the buildername already includes the repo name, and I shouldn't be required to repeat that.

**Comment by armenzg** [comment]
You're right. Thanks for reporting this.

@MikeLing do you have time to look into helping Xidorn?

**Comment by adusca** [comment]
https://github.com/mozilla/mozilla_ci_tools/pull/390#issuecomment-162002475

**Comment by MikeLing** [comment]
yep, I will look more into this :)

**Comment by armenzg** [comment]
@upsuper we've fixed this in the dot release I just made.
Thanks for reporting!
