### ISSUE TITLE
The trigger by filter functionality always shows the same list of builders even with --existing-only

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#412]
The script triggerbyfilters.py (soon to be merged with trigger.py) always shows the same list of builders to the users regardless if they use "--existing-only" or not:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/scripts/triggerbyfilters.py#L115

    if options.existing_only:
        cont = raw_input("The ones which have existing builds out of %i jobs will be triggered,\
                         do you wish to continue? y/n/d (d=show details) " % len(buildernames))
    else:
        cont = raw_input("%i jobs will be triggered, do you wish to continue? \
                          y/n/d (d=show details) " % len(buildernames))

We should fix this.

**Comment by armenzg** [comment]
We might have lost the functionality somewhere https://github.com/mozilla/mozilla_ci_tools/commit/d5d914ee98c53ecffae4577577b168722a57a10e

**Comment by MikeLing** [comment]
@armenzg Hmm, So how could we know if the build has been completed or not? Do we have any api or method or got that? I found the way we used in trigger_missing_job function is just trigger every build test no matter is completed or no.

**Comment by armenzg** [comment]
This is actually tough to do without taking a lot of computation time (e.g. calling determine_trigger_objective for every builder).

I think it would be better time spent trying to make determine_trigger_objective() to work with treeherder instead of being forced to use the BuildApi() [1]

In general, querying metadata about jobs through BuildApi is very expensive while using treeherder can be less accurate.

Would you like to work in such support and close this bug?
In my next quarter I hope to fix the accuracy of Treeherder by switching Buildbot jobs to be scheduled via BBB.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L139

**Comment by MikeLing** [comment]
Sure, let me close it and please tell me if there are anything I could help:)

Thank you armenzg.
