### ISSUE TITLE
Try out new authentication approach for taskcluster

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#413]
Once https://github.com/taskcluster/taskcluster-client.py/pull/33 lands, the taskcluster python client will have taskcluster.authenticate() which opens a browser and authenticates using login.tn and the "grant access" button.

Let's see if we can make this work.

There's some more info in here:
https://groups.google.com/forum/#!topic/mozilla.tools.taskcluster/xNZHBSZiy50

**Comment by armenzg** [comment]
@ahal has some projects coming down the pipeline which would benefit from this.

The idea is that if a developer has scm_level and they authenticate, they get a bunch of scopes assigned to them and they would be able to schedule TaskCluster tasks directly from the command line.

We're looking into adding some new tricks to mach to do this.

**Comment by martiansideofthemoon** [comment]
@armenzg hey! I would like to start working on this. I found the bug title a bit non-specific, so where could I begin figuring this out?

**Comment by armenzg** [comment]
We experimented with this in https://github.com/armenzg/TC_developer_scheduling_experiments/blob/master/schedule_linux64_task.py#L18
