### ISSUE TITLE
the buildbot_to_taskcluster has been broken

### ISSUE THREAD

**Issue by MikeLing** [mozilla/mozilla_ci_tools#421]
If you use
> python mozci/scripts/buildbot_to_taskcluster.py --trigger-from-task-id E8ReTsofQcujc9iSTmaR7A --repo-name try --revision c916d035c657 --builders "['Ubuntu VM 12.04 x64 try debug test mochitest-4']" --dry-run --debug

to test the buildbot_to_taskcluster and you will find a error will shows up like:

> Traceback (most recent call last):
>  File "mozci/scripts/buildbot_to_taskcluster.py", line 126, in <module>    main()
>  File "mozci/scripts/buildbot_to_taskcluster.py", line 101, in main
>    dry_run=options.dry_run
>  File "/Users/mikeling/mozilla_ci_tools/mozci/sources/buildbot_bridge.py", line 505, in trigger_builders_based_on_task_id
>     required_task_ids=required_task_ids,
> TypeError: generate_task_graph() takes at least 3 arguments (2 given)

I suppose the error is comes from https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/buildbot_bridge.py#L378. We may need to give a 'metadata' data for it or at least set a default value for metadata in https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/tc.py#L274.

**Comment by MikeLing** [comment]
@armenzg

**Comment by armenzg** [comment]
Thankfully this regression was only introduced yesterday. [1]
I wonder how I did not catch it.

Thanks @MikeLing I will fix it

[1] https://github.com/mozilla/mozilla_ci_tools/commit/b43a3c19fb751d5826586539ac438afe1112c998#diff-97b1ad150590d9b7fcb8e6bab49c28d5L279

**Comment by armenzg** [comment]
I pushed a fixed.
Let me know if it got fixed.
