### ISSUE TITLE
Unable to add new jobs within treeherder

### ISSUE THREAD

**Issue by parkouss** [mozilla/mozilla_ci_tools#422]
So, I'm not sure if it is the right place for reporting this, and maybe it is a duplicate - feel free to close it if this is the case;

So I pushed to try https://treeherder.mozilla.org/#/jobs?repo=try&revision=da728cb1294e. Now I missed something in the try syntax, so I want to trigger new jobs, that is some talos jobs for the Linux64 and Win32/64 jobs. I used the interface for that, and went to a final 'trigger request sent' message. But nothing appears; Also @jmaher tried without success.

**Comment by armenzg** [comment]
Hi @parkouss I hope to start looking into issues like this soon. I filed it under pulse_actions which processes treeherder requests:
https://github.com/mozilla/pulse_actions/issues/47

**Comment by parkouss** [comment]
Thanks @armenzg for the answer, and for moving the bug at the right place!
