### ISSUE TITLE
Make determine_trigger_job be able to work without BuildApi()

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#426]
Currently, to determine what to trigger, we need to talk with BuildApi() and grab all sorts of buildjson files. Fetching these files over network end up taking too much time.

We should be able to change determine_trigger_job() to work with treeherder [1]. Even if treeherder data can be less accurate.

In my next quarter I hope to fix the accuracy of Treeherder by switching Buildbot jobs to be scheduled via BBB.

@MikeLing let me know if you would be interested on this bug.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L139

**Comment by MikeLing** [comment]
Oh, sorry! I just see this issue and somehow I miss the notification from github :(

I haven't read it in detail, but I would like to happy of course ;)

**Comment by armenzg** [comment]
Yay! Thanks @MikeLing . This might be a tough one (or an ugly issue :P).

**Comment by armenzg** [comment]
Adding notes about using TaskCluster to find files:
########################################
<armenzg> mikeling, what I was telling you about TC, we can use the index to find tasks with artifacts
<armenzg> *every* buildbot job build uploads to TC
<armenzg> it's a neat dark secret
<armenzg> for instance, for a given revision
<armenzg> e.g. https://tools.taskcluster.net/index/#gecko.v2.mozilla-inbound.revision.0003682e05b93a1ce2f226665b848d25f12f3919.firefox/gecko.v2.mozilla-inbound.revision.0003682e05b93a1ce2f226665b848d25f12f3919.firefox.linux64-debug
<armenzg> and a platform
<armenzg> we can get to this task https://tools.taskcluster.net/task-inspector/#t1dd870CQsWqlVFB_qo0ag/
<armenzg> which has *all* the files we want https://tools.taskcluster.net/task-inspector/#t1dd870CQsWqlVFB_qo0ag/0
<armenzg> :)
<armenzg> in other words, given a Linux builder that comes from treeherder's data
<armenzg> we could determine the platform (e.g. linux64-debug)
<armenzg> we can add the functionality to say that it should be "firefox"
<armenzg> and we can establish the URL to the index
<armenzg> and the index can tell us which task contains all the artifacts

**Comment by MikeLing** [comment]
I got some progress on this :)

I think we could use this client[1] in mozci_tool to interact with taskcluster and we can easily get json data like https://index.taskcluster.net/v1/task/gecko.v2.mozilla-inbound.revision.0003682e05b93a1ce2f226665b848d25f12f3919.firefox.linux64-debug :) 

I will go ahead look more into this and figure out which file we need to trigger job. I think we need use these api in SETA also ;)

[1]https://github.com/taskcluster/taskcluster-client.py

**Comment by MikeLing** [comment]
Hey @armenzg, could you tell me more about the packageUrl and testPackagesUrl in https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L297-L303. Because I'm not sure which artifacts we want from https://tools.taskcluster.net/task-inspector/#t1dd870CQsWqlVFB_qo0ag/0

**Comment by armenzg** [comment]
We use taskcluster-client inside of the module tc.py

package url is normally the firefox tar ball (linux) [1], zip file (Windows), dmg file (Mac) and apk (Android)
test url is the tests.zip which contains all tests (we're deprecating this).
test packages url is a json [2] file which contains metadata of smaller zip files.

When a test job is running, it won't need to download all test zip files but can use the test_packages.json as a way to get to the zip files it needs.

[1] https://queue.taskcluster.net/v1/task/t1dd870CQsWqlVFB_qo0ag/runs/0/artifacts/public%2Fbuild%2Ffirefox-43.0a1.en-US.linux-x86_64.tar.bz2
[2] https://public-artifacts.taskcluster.net/t1dd870CQsWqlVFB_qo0ag/0/public/build/test_packages.json

**Comment by MikeLing** [comment]
@armenzg , the build_jobs in here[1] is empty when I use 

> python mozci/scripts/trigger.py --repo-name mozilla-inbound --revision "b125b74ee12b" -b "Ubuntu VM > large 12.04 x64 mozilla-inbound opt test gtest" --dry-run --debug

to test it. Could you tell me why? I haven't notice that before, could you give me a example that I can have some build jobs in it? Thank you :)

[1]:https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L164

**Comment by armenzg** [comment]
Hi @MikeLing you have probably found a regression we have.
Do you have time to look into it? [1] I used a Windows 8 64-bit builder since the build for the Windows 7 32-bit completed.

[1] https://gist.github.com/armenzg/d28af14c690932fdf195

**Comment by MikeLing** [comment]
Hi @armenzg , I can't got any build job by 'Windows 8 64-bit builder'.

The thing I do is add an output like **LOG.debug("List of matching jobs is %s" % build_jobs)** in this line[1] and I got **List of matching jobs is []** by "Windows 8 64-bit mozilla-central opt test gtest"
BTW, could you tell me some more about regression? why there's no build job if it's a regression build? Thank you :)

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/mozci.py#L171

**Comment by armenzg** [comment]
It seems that I called the script incorrectly.
I should have used 'Windows 8 64-bit mozilla-**inbound** opt test gtest'

Could you try again when you see this message? I don't have a good connection at the moment.

**Comment by MikeLing** [comment]
@armenzg , I got the job data now! Thank you :)

> package url is normally the firefox tar ball (linux) , zip file (Windows), dmg file (Mac) and apk (Android)

But how could we know which is the right file we want to achieve? Even we could queue a list of artufacts' name from https://queue.taskcluster.net/v1/task/t1dd870CQsWqlVFB_qo0ag/runs/0/artifacts, there aren't some tags or similar thing could help us find out which is **package url we want** and which is **the test json contain the whole test url**.

**Comment by armenzg** [comment]
It is going to be a bit hacky.
Mozharness does something similar.

You can see finding test_packages.json [1][2]

For installers you could also use constants for the suffixes [3] and do a similar approach as this for/loop [4]. The installer is the one that is not matched in the previous if/else statements. We will need a good test for this.
You can also see in here how in building firefox

Perhaps the right fix is to get it fixed in mozdownload, however, we can fix it first here and then port it there (and make mozdownload a dependency of mozci). You can see some inspirying code in here [5]. There are also some build regexes in here [6]

[1] https://dxr.mozilla.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/testing/testbase.py#323
[2] https://dxr.mozilla.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/taskcluster_helper.py#250
[3] https://dxr.mozilla.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/testing/testbase.py#33
[4] https://dxr.mozilla.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/testing/testbase.py#327
[5] https://github.com/mozilla/mozdownload/issues/365#issuecomment-180283713
[6] https://github.com/mozilla/mozregression/blob/68df78fe694beb6e9dc9abe848bf2c7f53a1f1db/mozregression/fetch_build_info.py#L147-L161
[7] https://github.com/mozilla/mozregression/blob/3fbd0421611a5f5816c7c50f4692a69c20d956c3/mozregression/fetch_configs.py#L44

**Comment by armenzg** [comment]
Hi @MikeLing I've noticed that this whole time we have been dealing with a Buildbot task [1] rather than a TaskCluster task [2].
Buildbot *build* jobs create a task to which they upload artifacts to. Thus, it looks like it was a TaskCluster job (rather than just where some artifacts got uploaded to).

With TaskCluster tasks, we get "target.<extension>" which makes determining the installer file name easily.

I hope this helps!

[1] https://tools.taskcluster.net/task-inspector/#t1dd870CQsWqlVFB_qo0ag/
[2] https://tools.taskcluster.net/task-inspector/#WpQ6sxBkRcicc19txj3-vQ/0

**Comment by MikeLing** [comment]
hi @armenzg , not related with this issue, but I meet some problem when I try to add test for tc.py. here is the things I got for now https://gist.github.com/MikeLing/1de0c9ac75525764c14ec50048b0ec81

>
>=================================== FAILURES >===================================
_________________ TestGenerateMetadata.test_generate_metadata __________________
>
>self = test_tc.TestGenerateMetadata testMethod=test_generate_metadata
query_repo_url = MagicMock name='query_push_by_revision' id='4395761040'
query_push_by_revision = MagicMock name='query_repo_url' id='4395742416'
>
    @patch('mozci.repositories.query_repo_url',
           return_value=mock_get(MOCK_REPO_URL % {'repo_name': 'repo1'}))
    @patch('mozhginfo.pushlog_client.query_push_by_revision',
           return_value=mock_push(MOCK_REVISION))
    def test_generate_metadata(self, query_repo_url, query_push_by_revision):
        response = {
            'name': self.name,
            'description': self.description,
            'owner': 'nobody@mozilla.com',
            'source': '%s/rev/%s' % (MOCK_REPO_URL, self.revision)
        }
        self.assertEqual(response,
                         tc.generate_metadata(repo_name=self.repo_name,
                                              revision=self.revision,
       >                                             name=self.name))

>

why it keeps telling me **'ValueError: No JSON object could be decoded'** which I don't have json.decoder in there?

**Comment by armenzg** [comment]
We can live without this.
