### ISSUE TITLE
Improve --help for trigger.py script

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#427]
We currently have multiple modes on trigger.py, however, when we list the help output we mix options which are *only* valid for some mode with all the other ones.

Think of hg.
If you type hg --help, it will list you all commands available (e.g. add)
If you type hg add --help, it will *only* list help that is related only to that mode.

**Comment by MikeLing** [comment]
yeah, I understand it's a very annoying thing when you want to search help for a special command but you got whole help list. But in trigger.py we define those command as an 'option'(I'm not sure if it's a good words to describe it), which means all these commands are in same level. So I'm not sure if we can do the same thing like 'hg --help' and 'hg add --help'.

**Comment by armenzg** [comment]
We should be able to.
We just need to look at what argparse allows us to do.

I also get confused with the term 'option' and other related argparse concepts.

**Comment by armenzg** [comment]
We don't use the scripts as much.
We can live without this.
