### ISSUE TITLE
--trigger-only-test-jobs does not do work properly

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#429]
In this push:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=cd403eeef6ad
there are no Buildbot jobs.

Calling trigger.py with --trigger-only-test-jobs should *not* try to schedule any jobs since there are no Buildbot builds completed (as the help says).
>  --trigger-only-test-jobs
>                        Schedule all missing tests for existing builds.

The code reached is this:
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/scripts/trigger.py#L320

armenzg@armenzg-thinkpad:~/repos/ci_tools$ python mozci/scripts/trigger.py --query-source treeherder --repo-name try --revision cd403eeef6ad --times 5 --trigger-only-test-jobs --dry-run
01/22/2016 11:34:26 root INFO:	Setting INFO level
01/22/2016 11:34:30 mozci INFO:	We want to have 1 job(s) of Ubuntu VM 12.04 try debug test crashtest-e10s on these revisions: 
01/22/2016 11:34:30 mozci INFO:	cd403eeef6ad7e391c22a3910f99c98ca03c4c0a
01/22/2016 11:34:30 mozci INFO:	
01/22/2016 11:34:30 mozci INFO:	=== cd403eeef6ad7e391c22a3910f99c98ca03c4c0a ===
01/22/2016 11:34:36 mozci INFO:	We want to have 1 job(s) of Ubuntu VM 12.04 try debug test crashtest-e10s
01/22/2016 11:34:37 mozci INFO:	We have found 0 potential job(s) matching 'Ubuntu VM 12.04 try debug test crashtest-e10s' on cd403eeef6ad7e391c22a3910f99c98ca03c4c0a. We need to trigger more.
01/22/2016 11:34:37 mozci INFO:	===> We want to trigger 'Ubuntu VM 12.04 try debug test crashtest-e10s' on revision 'cd403eeef6ad7e391c22a3910f99c98ca03c4c0a' a total of 1 time(s).
01/22/2016 11:34:37 mozci INFO:	
01/22/2016 11:34:39 mozci INFO:	We would have to triggered build 'Linux try leak test build' in order to trigger job 'Ubuntu VM 12.04 try debug test crashtest-e10s'. On this mode we will not trigger either.
01/22/2016 11:34:39 mozci INFO:	We want to have 1 job(s) of Windows 8 64-bit try opt test mochitest-browser-chrome-7 on these revisions: 
01/22/2016 11:34:39 mozci INFO:	cd403eeef6ad7e391c22a3910f99c98ca03c4c0a
01/22/2016 11:34:39 mozci INFO:	
01/22/2016 11:34:39 mozci INFO:	=== cd403eeef6ad7e391c22a3910f99c98ca03c4c0a ===
01/22/2016 11:34:39 mozci INFO:	We want to have 1 job(s) of Windows 8 64-bit try opt test mochitest-browser-chrome-7
01/22/2016 11:34:40 mozci INFO:	We have found 0 potential job(s) matching 'Windows 8 64-bit try opt test mochitest-browser-chrome-7' on cd403eeef6ad7e391c22a3910f99c98ca03c4c0a. We need to trigger more.
01/22/2016 11:34:40 mozci INFO:	===> We want to trigger 'Windows 8 64-bit try opt test mochitest-browser-chrome-7' on revision 'cd403eeef6ad7e391c22a3910f99c98ca03c4c0a' a total of 1 time(s).
01/22/2016 11:34:40 mozci INFO:	
01/22/2016 11:34:40 mozci INFO:	We would have to triggered build 'WINNT 6.1 x86-64 try build' in order to trigger job 'Windows 8 64-bit try opt test mochitest-browser-chrome-7'. On this mode we will not trigger either.
01/22/2016 11:34:40 mozci INFO:	We want to have 1 job(s) of Android 4.3 armv7 API 11+ try debug test plain-reftest-41 on these revisions: 
01/22/2016 11:34:40 mozci INFO:	cd403eeef6ad7e391c22a3910f99c98ca03c4c0a
01/22/2016 11:34:40 mozci INFO:	
01/22/2016 11:34:40 mozci INFO:	=== cd403eeef6ad7e391c22a3910f99c98ca03c4c0a ===
01/22/2016 11:34:40 mozci INFO:	We want to have 1 job(s) of Android 4.3 armv7 API 11+ try debug test plain-reftest-41

**Comment by mandaltapesh** [comment]
@armenzg   mozilla_ci_tools has been restructured ..so can you please update the bug info(the link to code and the terminal command) if possible :)

Have been busy off late , that is the cause of delay

**Comment by armenzg** [comment]
@mandaltapesh please give it a try to figurying out the links.

I've just pushed new code that makes the call like this (only "mozci/" has been dropped):
```
python scripts/trigger.py --query-source treeherder --repo-name try \
   --revision cd403eeef6ad --times 5 --trigger-only-test-jobs --dry-run
```

**Comment by armenzg** [comment]
We don't use the scripts anymore.
We can live without this.
