### ISSUE TITLE
Mozici return none of metadata when schdule job by taskcluster. 

### ISSUE THREAD

**Issue by MikeLing** [mozilla/mozilla_ci_tools#430]
As @armenzg mentioned in https://github.com/mozilla/mozilla_ci_tools/pull/390#issuecomment-173973348, mozici tool return none of metadata when it schdule job by taskcluster.
<pre><code>
1/23/2016 10:37:15 mozci INFO:	Outputting the graph:
{
    "scopes": [
        "queue:define-task:buildbot-bridge/buildbot-bridge", 
        "scheduler:create-task-graph"
    ], 
    "tasks": [
        {
            "reruns": 0, 
            "taskId": "Y1F6HKfYQIOS6hKIpF8G0g", 
            "task": {
                "scopes": [], 
                "extra": {}, 
                "expires": "2016-01-24T02:37:04.018592Z", 
                "schedulerId": "task-graph-scheduler", 
                "deadline": "2016-01-24T02:37:04.018574Z", 
                "payload": {
                    "sourcestamp": {
                        "branch": "try", 
                        "revision": "cd403eeef6ad7e391c22a3910f99c98ca03c4c0a"
                    }, 
                    "properties": {
                        "upload_to_task_id": "PNVm_rk_Sr6I6IY0nGuFPw", 
                        "product": "mobile", 
                        "who": "armenzg@mozilla.com"
                    }, 
                    "buildername": "Android armv7 API 11+ try debug build"
                }, 
                "provisionerId": "buildbot-bridge", 
                "workerType": "buildbot-bridge", 
                "retries": 5, 
                "created": "2016-01-23T02:37:04.018531Z", 
                "tags": {}, 
                "priority": "normal", 
                "routes": [], 
                "metadata": {
                    "owner": "armenzg@mozilla.com", 
                    "source": "https://hg.mozilla.org/try/rev/cd403eeef6ad7e391c22a3910f99c98ca03c4c0a", 
                    "name": "Android armv7 API 11+ try debug build", 
                    "description": "Task graph generated via Mozilla CI tools"
                }
            }
        }, 
        {
            "reruns": 0, 
            "requires": [
                "Y1F6HKfYQIOS6hKIpF8G0g"
            ], 
            "taskId": "ccywsjMASSC4ch2Y3IzRng", 
            "task": {
                "scopes": [], 
                "extra": {}, 
                "expires": "2016-01-24T02:37:15.111094Z", 
                "schedulerId": "task-graph-scheduler", 
                "deadline": "2016-01-24T02:37:15.111075Z", 
                "payload": {
                    "sourcestamp": {
                        "branch": "try", 
                        "revision": "cd403eeef6ad7e391c22a3910f99c98ca03c4c0a"
                    }, 
                    "properties": {
                        "upload_to_task_id": "Osb649w1SWC0aBHpz02uig", 
                        "product": "mobile", 
                        "who": "armenzg@mozilla.com", 
                        "parent_task_id": "PNVm_rk_Sr6I6IY0nGuFPw"
                    }, 
                    "buildername": "Android 4.3 armv7 API 11+ try debug test plain-reftest-41"
                }, 
                "provisionerId": "buildbot-bridge", 
                "workerType": "buildbot-bridge", 
                "retries": 5, 
                "created": "2016-01-23T02:37:15.111039Z", 
                "tags": {}, 
                "priority": "normal", 
                "routes": [], 
                "metadata": {
                    "owner": "armenzg@mozilla.com", 
                    "source": "https://hg.mozilla.org/try/rev/cd403eeef6ad7e391c22a3910f99c98ca03c4c0a", 
                    "name": "Android 4.3 armv7 API 11+ try debug test plain-reftest-41", 
                    "description": "Task graph generated via Mozilla CI tools"
                }
            }
        }
    ], 
    "metadata": null
</code></pre>

I guess the problem is in here:
we use get 'metadata' in https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/buildbot_bridge.py#L382 and I guess it's suppose get from 'metadata' from kwargs and retrieve from generate_metadata function if there is not metadata been returned.

But, if you print kwargs in generate_builders_tc_graph, you will see we actually got metadata in there 

>  (Pdb) p kwargs
>{'metadata': None}
and I think the kwargs get just simple use the None and return it.

**Comment by armenzg** [comment]
Good catch!
I think it is fine to make metadata an optional argument rather than grab it through **kwargs.

**Comment by MikeLing** [comment]
I think this issue had been fixed in this PR(https://github.com/mozilla/mozilla_ci_tools/commit/63a1de3ad416f5f5fa1976ec931d22b67a344886) and we could close it now :)
