### ISSUE TITLE
Add tests to trigger.py

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#439]
I believe the script has become complicated enough that we should start adding tests for it.
Each mode should be tested with a couple of variances.

**Comment by MikeLing** [comment]
Maybe I can work on this :)

**Comment by armenzg** [comment]
This would be super awesome as we used to rely on manual testing and have not done much of it these days!

It might require moving certain "modes" into their own isolated functions to be able to test them.

**Comment by armenzg** [comment]
We can live without this.
