### ISSUE TITLE
Indicate the buildername when submitting a BBB task instead of 'pulse_actions_graph'

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#444]
In this graph:
https://tools.taskcluster.net/task-graph-inspector/#DdvObl_NR7KbNo48IUAI8w
You will see that every task is named 'pulse_graph'.
Instead, we should change this so it shows the buildername.

See one of the defined tasks:
https://queue.taskcluster.net/v1/task/flHe5_JPQK29jo6-h9H0Bw

Simply overwriting metadata['name'] should be sufficient.
https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/sources/buildbot_bridge.py#L98

We will need a new release for this.

@martiansideofthemoon this is an easy issue if you would like to get your feet wet fast.

**Comment by martiansideofthemoon** [comment]
@armenzg ,
sorry, i was afk.. Yup i got a basic idea.. I've never worked with python unittests in the past. I've written unittests for Gaia though in JS. I think I understood some basic things. But I'll be honest, I didn't quite get the @patch part well. I think I wasn't patient enough with the documentation.

**Comment by martiansideofthemoon** [comment]
@armenzg, yeah it makes sense now :smile: How was it relevant to the unit test i wrote?

**Comment by armenzg** [comment]
It wasn't! It was my bad.

In general, we try to use @patch to prevent calls to allthethings.json since it is a bad file to write tests agains (hitting diff maxs).

**Comment by armenzg** [comment]
I think this is now completed. Thanks @martiansideofthemoon
