### ISSUE TITLE
Make mozci tests network proof

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#446]
@martiansideofthemoon and I have noticed that the tox runs on Travis have become rather intermittent. Maybe there are some Mozilla infrastructure issues making things hard.

In order to make the mozci tests network proof we need to add mock object to the intermittent tests.
In order to find these tests, disable the wifi and run tox.

So far I've noticed a couple of tests giving headaches
TestBuildbotBridge.test_correct_name 
E           ConnectionError: HTTPSConnectionPool(host='secure.pub.build.mozilla.org', port=443): Max retries exceeded with url: /builddata/reports/allthethings.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ef3829c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))

TestBuildApiGetAllJobs.test_bad_revision 
...
E           ConnectionError: HTTPSConnectionPool(host='secure.pub.build.mozilla.org', port=443): Max retries exceeded with url: /buildapi/self-serve/try/rev/146071751b1e?format=json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ef2b66610>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by martiansideofthemoon** [comment]
@armenzg , I get the same failure on my PC. Does it happen for you locally?

**Comment by armenzg** [comment]
If I disable the WiFi I get the same issues locally. These tests will need some extra mocking so they won't hit the network.

**Comment by armenzg** [comment]
This is nice to have but it is not that bad. We can just rerun the Travis builds when they fail if they fail.
I was hoping this would help with the current test failures that martianwars just fixed.

Let's not work more than we need to! :smile:
