### ISSUE TITLE
Tox should run our tests with a set known of dependencies + the latest version of our dependencies

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#451]
By doing this, we can detect when a newly released python dependency starts causing the issues instead of our own changes.

Right now, we always test against the latest versions of our dependencies.

**Comment by F3real** [comment]
I'll try to do this.

**Comment by F3real** [comment]
@armenzg Should we close  this one ? Now when https://github.com/mozilla/mozilla_ci_tools/pull/453 landed.

**Comment by armenzg** [comment]
Yes! Sounds good.
