### ISSUE TITLE
get_buildername_metadata() doesn't work for pgo build

### ISSUE THREAD

**Issue by martiansideofthemoon** [mozilla/mozilla_ci_tools#468]
@armenzg when I run `get_buildername_metadata()` for a `pgo` build, I get `opt` as the `repo_name`. Shouldn't it be `pgo`?

**Comment by armenzg** [comment]
Would you mind pasting code output? It will be easier to discuss.
You can also use a python notebook if you prefer to share code + output.

**Comment by martiansideofthemoon** [comment]
On running `get_buildername_metadata()` for a PGO build, I get
```
{'product': u'firefox', 'downstream': True, 'job_type': 'talos', 'platform_name': u'win64-pgo', 'suite_name': u'other', 'build_type': 'opt', 'repo_name': u'fx-team'}
```
Shouldn't `build_type` be PGO?

**Comment by armenzg** [comment]
Yes, let's use the PR to follow up on this.
