### ISSUE TITLE
Improve PGO and nightly detection

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#471]
Yesterday we landed PGO classification of jobs (great!).
My graph generation script started failing due to the 'pgo' key missing, I landed a fix but that led me to dig deeper.
I've noticed in [2] that we mark many more builders as PGO than we intended to.

I also believe we should put nightly builds into their own category.

We also need to improve the relationships of l10n-nightly jobs to their associated nightly job.
For instance, "Android armv7 API 15+ mozilla-aurora l10n nightly-1" is a downstream job of "Android armv7 API 15+ mozilla-aurora nightly".
Right now, all l10n nightly jobs are showing up as upstream jobs (i.e. they don't depend on any other job).

[1] https://github.com/mozilla/mozilla_ci_tools/commit/593c6290c830188a7064746802ea5f7ec7e354b6
[2] https://gist.github.com/armenzg/c9dc36502babd1bd5f8d57f23271a0d3

**Comment by martiansideofthemoon** [comment]
@armenzg I'll try to work on this

**Comment by armenzg** [comment]
I've landed a big refactoring to get_buildername_metadata() and disabled the graphs test as I run out of time working on this.

In this issue could you look into the following items:
* Reactive the test which we're skipping after my latest change
* Look into making our tests run faster
  * The change to get rid of mock_allthethings.json made the runs slower
  * You can use py.test --durations=10 to find the slowest 10 tests

Thank you very much with your help with this!

**Comment by armenzg** [comment]
An error in my logic:
https://github.com/mozilla/mozilla_ci_tools/commit/9f14aebcf3255a12114076098ef6ce8b0ed5ea8d#diff-080760856cfeb3690166d07dd9636fdfR288
