### ISSUE TITLE
pytest-runner shouldn't be in install_requires

### ISSUE THREAD

**Issue by edmorley** [mozilla/mozilla_ci_tools#492]
Otherwise all consumers of the `mozci` package will end up installing it, when they don't need it.

It should go in `tests_require` instead.

In addition, the main packages shouldn't be listed in both `install_requires` and `tests_require` (the latter is intended as additions to the already installed, not a replacement for).

**Comment by edmorley** [comment]
See:
http://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords

**Comment by armenzg** [comment]
Thanks for pointing this out!

Do you have time to look into this?
