### ISSUE TITLE
Query jobdetails api instead of artifacts api for request id

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#498]
Assigning to @wlach 
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1303816 for details.
See the announcement:
https://groups.google.com/forum/#!topic/mozilla.tools/7b0kKoLGhak

**Comment by wlach** [comment]
This will be easy to fix when https://bugzilla.mozilla.org/show_bug.cgi?id=1303816 is fixed and we have a new version of treeherder client, hope to have this taken care of by tomorrow
