### ISSUE TITLE
tox.ini uses different Python package versions to setup.py

### ISSUE THREAD

**Issue by edmorley** [mozilla/mozilla_ci_tools#512]
Compare:
https://github.com/mozilla/mozilla_ci_tools/blob/147a8d16abdb7598363a11c6c36dec5f555064a1/setup.py#L4-L15

To:
https://github.com/mozilla/mozilla_ci_tools/blob/147a8d16abdb7598363a11c6c36dec5f555064a1/tox.ini#L20-L29

It seems like tox.ini should just use `.` to install the local dependencies from setup.py instead.

**Comment by edmorley** [comment]
(Context: tox.ini uses the older treeherder-client==2.0.1 unlike setup.py which uses v3)

**Comment by armenzg** [comment]
What you point out on tox.ini was intended to test against a fix set of dependencies (compared to the "new_deps" section https://github.com/mozilla/mozilla_ci_tools/blob/147a8d16abdb7598363a11c6c36dec5f555064a1/tox.ini#L38).
I'm happy to drop it all together and test against *latest* all the time.

Would this work for you?

Also, I believe we will soon be abandoning mozci/pulse_actions.

I think at the time we had been bit with some new package not being good. I can't remember.

**Comment by edmorley** [comment]
Pinning dependencies is often a good thing, but for a package that's intended to be consumed as is, the packages being tested should be those that the user will get when `pip install`ing the package. ie the pinning should occur in setup.py and not just on the test side. 

(Or more specifically, setup.py should use semver version ranges, rather than exact pinned versions)
