### ISSUE TITLE
Make the project flake8_docstrings compatible

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#96]
I would like us to add flake8 to the list of analytical tool to improve the project properness score.

We can initially start by trying to address all the issues raised by this:
flake8 mozci scripts test --ignore E501

**Comment by vaibhavmagarwal** [comment]
Working on this.

**Comment by armenzg** [comment]
An easy way to test this is by adding flake8_docstring to tox.ini
After that, run 'tox' and you will see all the failures.

**Comment by armenzg** [comment]
Instead of focusing on a specific file to fix up.
We can also focus on a specific type of failure.
The trick would be how to modify [flake] under tox.ini to exclude the errors we don't want to see.

For instance, we already have one modifier (line length):
```
[flake8]
exclude = .tox
show-source = True
max-line-length=100
```

**Comment by mandaltapesh** [comment]
hi all,
i opened a PR for this https://github.com/mozilla/mozilla_ci_tools/pull/432

**Comment by armenzg** [comment]
In #432 tapesh added support for flake8 docstrings, however, a lot of warnings were disable at the same time [1]

We would like to remove most of those warnings to improve the quality of the documentation of the project and hopefully the quality.

[1] https://github.com/mozilla/mozilla_ci_tools/blob/master/tox.ini#L23
