### ISSUE TITLE
Use cProfile to determine where we are slow and improve code execution

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozilla_ci_tools#99]
I would like to start looking as to which methods are called most often and how long each takes.
That way we can start looking at how to optimize the project to reduce code execution.

For instance, we have an issue where we're trying to reduce how many times we read repositories.txt from disk.

This would be useful if I call a script and I can specify something like --code-execution and it generates a report.

I have no experience about this so I might even be talking non-sense.

There is no rush for this.

**Comment by adusca** [comment]
Have you tried cProfile? https://docs.python.org/2/library/profile.html
https://pastebin.mozilla.org/8824713 is the output I get when running
python -m cProfile -s cumulative scripts/trigger.py --rev 4f2decfeb9c5 -b "Rev5 MacOSX Mountain Lion 10.8 try talos svgr" --dry-run

**Comment by armenzg** [comment]
This is exactly what we need!
We should look at where we are slow and optimize. It seems that there is a lot of room for improvements.

**Comment by armenzg** [comment]
@xennygrimmato if you're interested in this. I would try running one or two different ways that script and see if you find any bottlenecks.

However, we're hoping to move from using Buildapi to TaskCluster to scheduling jobs. With this being said, do not try to analyze anything around buildapi.

We can also look into switching from using Buildapi as a source of jobs to Treeherder (--query-source='treeherder'). I think that might be better use of your time than trying to optimize code that still talks to Buildapi.

* https://secure.pub.build.mozilla.org/buildapi/self-serve
* http://docs.taskcluster.net
* https://treeherder.readthedocs.org/en/latest/ http://treeherder.mozilla.org/

**Comment by xennygrimmato** [comment]
Cool, then I'd look at this some time later, if required.
